dataset:
  root: "./data"

training:
  dumb:
    enabled: false
    n_layers: 10
  learning_rate: 0.08
  lr_scheduler: true
  checkpoints_path: "./checkpoints"
  figures_path: "./figures"
  checkpoints_frequency: 25 # epochs
  train_fraction: 0.8
  batch_size: 8
  epochs: 100
  loss: "arc"
  val_every: 2 # epochs

test:
  enabled: true
  mindcf_p_target: 0.01
  mindcf_c_fa: 1
  mindcf_c_miss: 1
  num_speakers: 10
  num_utterances_per_speaker: 10

loss:
  sphere:
    margin: 4
  cos:
    margin: 0.2
    scale: 64
  arc:
    margin: 0.2
    scale: 30

titanet:
  embedding_size: 192
  model_size: "s"
  n_mega_blocks: false
  attention_hidden_size: 128
  simple_pool: false
  dropout: 0.5

wandb:
  enabled: false
  entity: "wadaboa"
  project: "titanet"
  api_key_file: "./init/wandb_api_key_file"

generic:
  seed: 42
  workers: 4
  log_console: false
  chart_dependencies: false

audio:
  sample_rate: 16000
  spectrogram:
    n_fft: 512
    win_length: 25 # ms
    hop_length: 10 # ms
    n_mels: 80

augmentation:
  rir_corpora_path: "./data/rirs"
  enable:
    - "chunk"
    - "specaugment"
  max_length: 3 # s
  chunk_lengths:
    - 1.5
    - 2
    - 3
  min_speed: 0.95
  max_speed: 1.05
  freq_mask_param: 100
  freq_mask_num: 1
  time_mask_param: 80
  time_mask_num: 1
  probability: 0.5
